### ISSUE TITLE
Exception PlayerChallengeCompleteEvent Enchantment challenge 

### ISSUE THREAD

**Issue by Fonkio** [nulli0n/GoldenChallenges#1]
Issue when an Enchantment Challenge is complete, message in the actionbar does not appear and an exception is raised :

**[12:11:37 ERROR]: Could not pass event PlayerChallengeCompleteEvent to GoldenChallenges v1.0.5**
> java.lang.IllegalArgumentException: Invalid key. Must be [a-z0-9/._-]: 
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:191) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.NamespacedKey.<init>(NamespacedKey.java:49) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.NamespacedKey.minecraft(NamespacedKey.java:142) ~[patched_1.16.3.jar:git-Paper-253]
        at su.nexmedia.goldenchallenges.manager.type.ChallengeJobType$Constants.lambda$4(ChallengeJobType.java:90) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.type.ChallengeJobType.formatObjective(ChallengeJobType.java:61) ~[?:?]
        at su.nexmedia.goldenchallenges.data.object.ChallengeUserProgress.lambda$4(ChallengeUserProgress.java:92) ~[?:?]
        at su.nexmedia.engine.config.api.ILangTemplate$JLangMsg.replace(ILangTemplate.java:365) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.ChallengeListener.onChallengeCompleteEvent(ChallengeListener.java:94) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor294.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-253]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
        at su.nexmedia.goldenchallenges.data.object.ChallengeUser.lambda$4(ChallengeUser.java:157) ~[?:?]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[?:1.8.0_275]
        at su.nexmedia.goldenchallenges.data.object.ChallengeUser.progressChallenge(ChallengeUser.java:154) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.ChallengeManager.progressChallenge(ChallengeManager.java:127) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.ChallengeListener.lambda$3(ChallengeListener.java:208) ~[?:?]
        at java.util.HashMap.forEach(HashMap.java:1289) ~[?:1.8.0_275]
        at su.nexmedia.goldenchallenges.manager.ChallengeListener.onChallengeItemEnchant(ChallengeListener.java:207) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor296.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.3.jar:git-Paper-253]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.3.jar:git-Paper-253]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.ContainerEnchantTable.lambda$a$1(ContainerEnchantTable.java:246) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.ContainerAccess.lambda$a$0(ContainerAccess.java:59) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.ContainerAccess$2.a(ContainerAccess.java:46) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.ContainerAccess.a(ContainerAccess.java:58) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.ContainerEnchantTable.a(ContainerEnchantTable.java:230) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PlayerConnection.a(PlayerConnection.java:2553) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PacketPlayInEnchantItem.a(SourceFile:22) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PacketPlayInEnchantItem.a(SourceFile:8) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:23) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.TickTask.run(SourceFile:18) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.ba(MinecraftServer.java:1135) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.executeNext(MinecraftServer.java:1128) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.sleepForTick(MinecraftServer.java:1089) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:1003) ~[patched_1.16.3.jar:git-Paper-253]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Paper-253]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]

**Comment by nulli0n** [comment]
Provide your config for enchantment challenges.

**Comment by Fonkio** [comment]
Hi,
It's the default config, I haven't changed anything
My plugin folder on a test server :
[plugins.zip](https://github.com/nulli0n/GoldenChallenges/files/5588861/plugins.zip)

**Comment by nulli0n** [comment]
Should be fixed now.

**Comment by Fonkio** [comment]
Yes ! Thank you
