### ISSUE TITLE
NPC Error

### ISSUE THREAD

**Issue by Khosraw** [nulli0n/GoldenChallenges#4]
I'm getting the following error spammed in the console:

`[15:44:27 ERROR]: Could not pass event EntityDamageEvent to GoldenChallenges v1.1.0
java.lang.IllegalStateException: Could not load user data from an NPC!
        at su.nexmedia.engine.data.users.IUserManager.getOrLoadUser(IUserManager.java:119) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.ChallengeManager.progressChallenge(ChallengeManager.java:120) ~[?:?]
        at su.nexmedia.goldenchallenges.manager.ChallengeListener.onChallengeDamageReceiveInflict(ChallengeListener.java:224) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1009.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.16.5.jar:git-Paper-475]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEvent(CraftEventFactory.java:247) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callEntityDamageEvent(CraftEventFactory.java:1067) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:1049) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleEntityDamageEvent(CraftEventFactory.java:910) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.handleLivingEntityDamageEvent(CraftEventFactory.java:1099) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity0(EntityLiving.java:1838) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity0(EntityHuman.java:842) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityLiving.damageEntity(EntityLiving.java:1166) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityHuman.damageEntity(EntityHuman.java:759) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityPlayer.damageEntity(EntityPlayer.java:842) ~[patched_1.16.5.jar:git-Paper-475]
        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.damageEntity(EntityHumanNPC.java:155) ~[?:?]
        at net.minecraft.server.v1_16_R3.MobEffectList.tick(MobEffectList.java:47) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MobEffect.a(SourceFile:169) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MobEffect.tick(SourceFile:148) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityLiving.tickPotionEffects(EntityLiving.java:719) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.EntityLiving.entityBaseTick(EntityLiving.java:363) ~[patched_1.16.5.jar:git-Paper-475]
        at net.citizensnpcs.nms.v1_16_R3.entity.EntityHumanNPC.playerTick(EntityHumanNPC.java:373) ~[?:?]
        at net.citizensnpcs.nms.v1_16_R3.util.NMSImpl.playerTick(NMSImpl.java:974) ~[?:?]
        at net.citizensnpcs.util.NMS.playerTick(NMS.java:340) ~[?:?]
        at net.citizensnpcs.util.PlayerUpdateTask.run(PlayerUpdateTask.java:56) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Paper-475]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MinecraftServer.b(MinecraftServer.java:1294) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.DedicatedServer.b(DedicatedServer.java:377) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1209) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:997) ~[patched_1.16.5.jar:git-Paper-475]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:174) ~[patched_1.16.5.jar:git-Paper-475]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_275]`

How can I remove the instance of that NPC to fix this error?

**Comment by nulli0n** [comment]
Will be fixed!

**Comment by nulli0n** [comment]
Should be fixed now

**Comment by nulli0n** [comment]
Fixed.
